server:
  port: 8040

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    sql:
      init:
        mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
        root-directory: ${S3_ROOT_DIRECTORY}
        thumbnail-directory: ${S3_THUMBNAIL_DIRECTORY}
      cloudfront:
        distribution-domain: ${CLOUDFRONT_DISTRIBUTION_DOMAIN}