server:
  port: 8040

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

    open-in-view: false
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  jwt:
    secret: ${JWT_SECRET}
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET}
        root-directory: ${S3_ROOT_DIRECTORY}
        thumbnail-directory: ${S3_THUMBNAIL_DIRECTORY}
        representation-directory: ${S3_REPRESENTATION_DIRECTORY}
      region:
        static: ${S3_REGION}
      stack:
        auto: false
      cloudfront:
        distribution-domain: ${CLOUDFRONT_DISTRIBUTION_DOMAIN}
        jdbc:
          time_zone: Asia/Seoul
          show_sql: true
          format_sql: true
        ddl-auto: ${SPRING_DATASOURCE_DDL_AUTO}
    repositories:
        enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: trace

